// Current source inventory is explicit: adding a resource requires a reviewed
// contract update. Historical cutover inventories live in their pinned fixtures.
export const canonicalEntityNames: readonly string[] = Object.freeze([
  "AiGenerationQuota",
  "AiGenerationUsage",
  "AiWordPackCacheVariant",
  "AiWordPackOperation",
  "AiWordPackRequestResult",
  "AppStoreAccount",
  "AppleSignInCredential",
  "BillingIdentityLifecycle",
  "CommunityProfileSignal",
  "CommunityReport",
  "Entitlement",
  "Friendship",
  "GameHistory",
  "GameRoom",
  "GameRoomSignal",
  "LiveActivityRegistration",
  "MembershipGrant",
  "MembershipSignal",
  "NotificationAnnouncement",
  "NotificationReadReceipt",
  "ProfileComment",
  "PushDeviceRegistration",
  "PushNotificationEvent",
  "RoomInvite",
  "User",
  "WordPack",
]);

export const canonicalFunctionNames: readonly string[] = Object.freeze([
  "advanceRound",
  "app-store-entitlement",
  "appleAuthBroker",
  "appleAuthCallback",
  "autoRegisterUser",
  "checkSubscription",
  "communityAction",
  "createCheckout",
  "deleteAccount",
  "gameRoomAction",
  "generateWordPack",
  "googleAuthCallback",
  "mobileAuthCallback",
  "notificationAction",
  "pushNotificationAction",
  "stripe-entitlement-webhook",
  "wordPackAction",
]);
